name: build-image

on:
  push:
    tags:
    - '*'
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Tag for the image to build'
        required: true
        default: latest

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

env:
  IMAGE_TAG: ${{ inputs.image_tag || github.ref_name }}

jobs:

  check-uv-lock:
    name: Check if uv lock is up to date
    runs-on: ubuntu-latest
    steps:
    - name: Clone edh-catalogue-deploy repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GIT_PAT }}
        path: bopen/edh-catalogue-deploy
    - name: Load environment variables from environment.release file
      run: |
        # grep -v '^#' ignores comment lines
        # grep -v '^$' ignores empty lines
        grep -v '^#' bopen/edh-catalogue-deploy/environment.release | grep -v '^$' >> $GITHUB_ENV
    - name: Clone edh-catalogue-api and edh-catalogue-manager repositories
      uses: bopen/ci-cd/git-clone@main
      with:
        repo-list: "bopen/edh-catalogue-api bopen/edh-catalogue-manager"
        git-pat: ${{ secrets.GIT_PAT }}
    - name: Check if uv lock is up to date
      id: check_uv_lock
      run: |
        cd bopen/edh-catalogue-deploy
        uv lock --check && UV_CHECK='ok' || UV_CHECK='not_ok'
        echo "UV_CHECK=$UV_CHECK" >> $GITHUB_OUTPUT
        cat $GITHUB_OUTPUT
    # - name: Checkout update-uv-lock branch
    #   if: steps.check_uv_lock.outputs.UV_CHECK == 'not_ok'
    #   run: |
    #     cd bopen/edh-catalogue-deploy
    #     git config user.name "github-actions"
    #     git config user.email ""
    #     git fetch origin
    #     if git ls-remote --exit-code origin update-uv-lock; then
    #       echo "Branch update-uv-lock already exists, checking it out."
    #       git checkout update-uv-lock
    #     else
    #       echo "Branch update-uv-lock does not exist, creating it."
    #       git checkout -b update-uv-lock
    #     fi
    - name: Update uv lock
      if: steps.check_uv_lock.outputs.UV_CHECK == 'not_ok'
      run: |
        cd bopen/edh-catalogue-deploy
        uv lock
    # - name: Commit and push uv lock changes
    #   if: steps.check_uv_lock.outputs.UV_CHECK == 'not_ok'
    #   run: |
    #     cd bopen/edh-catalogue-deploy
    #     git diff
    #     git add uv.lock
    #     git commit -m "🤖 Update uv lock" || echo "Nothing to commit"
    #     git push origin update-uv-lock --force
    - name: Create Pull Request
      if: steps.check_uv_lock.outputs.UV_CHECK == 'not_ok'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GIT_PAT }}
        commit-message: "🤖 Update uv lock"
        title: "🤖 Update uv lock"
        body: "This Pull Request has been automatically created by the workflow to update the uv lock file."
        base: main
        branch: update-uv-lock
        path: bopen/edh-catalogue-deploy
        assignees: francesconazzaro
    - name: Fail if uv lock is not up to date
      if: steps.check_uv_lock.outputs.UV_CHECK == 'not_ok'
      run: |
        echo "A Pull Request has been opened to update the uv lock file."
        exit 1

  build-docker-image:
    name: Build edh-catalogue-api:${{ inputs.image_tag || github.ref_name }}
    needs: check-uv-lock
    runs-on: ubuntu-latest
    steps:
    - name: Harbor login
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.HARBOR_URL }}
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        context: bopen
        file: bopen/edh-catalogue-deploy/Dockerfile
        build-args: |
          GIT_PAT=${{ secrets.GIT_PAT }}
        tags: |
          ${{ vars.HARBOR_URL }}/hedp/edh-catalogue-api:${{ env.IMAGE_TAG }}

  security-scan:
    name: Security scan edh-catalogue-api:${{ inputs.image_tag || github.ref_name }}
    runs-on: ubuntu-latest
    needs: build-docker-image
    steps:
    - name: Login to Harbor
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.HARBOR_URL }}
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.35.0
      with:
        image-ref: ${{ vars.HARBOR_URL }}/hedp/edh-catalogue-api:${{ env.IMAGE_TAG }}
        exit-code: '0'
        format: table
        ignore-unfixed: true
        vuln-type: os,library
        output: trivy-report-edh-catalogue-api-${{ github.run_id }}.txt
    - name: Upload Trivy Vulnerability Scan Results
      uses: actions/upload-artifact@v4
      with:
        name: trivy-report
        path: trivy-report-edh-catalogue-api-${{ github.run_id }}.txt
        retention-days: 30
    - name: Add Trivy report in the summary
      run: |
        echo "## Trivy report for edh-catalogue-api:${{ env.IMAGE_TAG }}" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        cat trivy-report-edh-catalogue-api-${{ github.run_id }}.txt >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

    - name: Run Grype scan
      uses: anchore/scan-action@v6
      with:
        image: ${{ vars.HARBOR_URL }}/hedp/edh-catalogue-api:${{ env.IMAGE_TAG }}
        fail-build: false
        output-format: table
        output-file: grype-report-edh-catalogue-api-${{ github.run_id }}.txt
    - name: Upload Grype Vulnerability Scan Results
      uses: actions/upload-artifact@v4
      with:
        name: grype-report
        path: grype-report-edh-catalogue-api-${{ github.run_id }}.txt
        retention-days: 30
    - name: Add Grype report in the summary
      run: |
        echo "## Grype report for edh-catalogue-api:${{ env.IMAGE_TAG }}" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        cat grype-report-edh-catalogue-api-${{ github.run_id }}.txt >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

  release-e2e:
    name: Trigger GitLab pipeline for release-edh-catalogue-api-e2e
    runs-on: ubuntu-latest
    needs: build-docker-image
    if: github.event_name == 'push'
    steps:
    - name: Trigger GitLab pipeline
      run: |
        curl -X POST -F "token=${{ secrets.DESP_GITLAB_TOKEN }}" \
             -F "ref=main" \
             -F "variables[EDH_CATALOGUE_API_E2E_TAG]=${{ env.IMAGE_TAG }}" \
             ${{ vars.DESP_GITLAB_URL }}
      env:
        DESP_GITLAB_TOKEN: ${{ secrets.DESP_GITLAB_TOKEN }}

  release-dev:
    name: Trigger GitLab pipeline for release-edh-catalogue-api-dev
    runs-on: ubuntu-latest
    needs: build-docker-image
    if: github.event_name == 'workflow_dispatch'
    steps:
    - name: Trigger GitLab pipeline
      run: |
        curl -X POST -F "token=${{ secrets.DESP_GITLAB_TOKEN }}" \
             -F "ref=main" \
             -F "variables[EDH_CATALOGUE_API_DEV_TAG]=${{ env.IMAGE_TAG }}" \
             https://forge.dev.desp.space/api/v4/projects/92/trigger/pipeline
      env:
        DESP_GITLAB_TOKEN: ${{ secrets.DESP_GITLAB_TOKEN }}
